const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const uid=p=>`${p}-${Date.now().toString(36)}${Math.random().toString(36).slice(2,6)}`;
const store={get(){return JSON.parse(localStorage.getItem('pitstopEventosV1')||'null')||seed()},set(d){localStorage.setItem('pitstopEventosV1',JSON.stringify(d));state=d}};
let state=store.get(), currentView='dashboard';
function seed(){const d={company:{name:'PITSTOP COHAB',address:'Av. Ana Jacinta, Nº 2039',city:'Presidente Prudente - SP',cnpj:'64.712.625/0001-69',phone:'+55 18 99623-8015',instagram:'@pitstopcohab'},products:[['Skol Lata 350ml',5],['Brahma Lata 350ml',5],['Heineken Lata 350ml',6.5],['Refrigerante 2L',8],['Energético 473ml',12],['Gelo 5kg',12],['Água 500ml',3]].map(x=>({id:uid('prod'),name:x[0],price:x[1],stock:300})),assets:[['Caixa Térmica 120L',150,12],['Mesa Plástica',30,20],['Cadeira Plástica',10,80],['Tenda 3x3',200,4]].map(x=>({id:uid('pat'),name:x[0],price:x[1],qty:x[2]})),events:[]};d.events=[{id:'EVT-000125',client:'João Silva',phone:'+55 18 99623-8015',date:'2026-06-15',start:'15:00',end:'03:30',address:'Rua das Flores, 123 - Jardim Primavera',notes:'Churrasco com amigos e familiares',deliveryFee:50,serviceFee:80,otherFee:0,status:'em_andamento',items:d.products.map((p,i)=>({productId:p.id,sent:[100,60,30,20,15,20,30][i],returned:[20,10,5,5,2,2,10][i]||0})),assets:[{assetId:d.assets[0].id,sent:2,returned:1},{assetId:d.assets[1].id,sent:3,returned:3},{assetId:d.assets[2].id,sent:10,returned:10},{assetId:d.assets[3].id,sent:1,returned:1}]}];localStorage.setItem('pitstopEventosV1',JSON.stringify(d));return d}
function calcEvent(e){let products=0,sent=0,consumed=0;for(const it of e.items){const p=state.products.find(x=>x.id===it.productId);const c=Math.max(0,(+it.sent||0)-(+it.returned||0));products+=c*(p?.price||0);sent+=(+it.sent||0)*(p?.price||0);consumed+=c}let missing=0;for(const a of e.assets){const p=state.assets.find(x=>x.id===a.assetId);missing+=Math.max(0,(+a.sent||0)-(+a.returned||0))*(p?.price||0)}const fees=(+e.deliveryFee||0)+(+e.serviceFee||0)+(+e.otherFee||0);return{products,sent,missing,fees,total:products+missing+fees,consumed}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function setView(v){currentView=v;$$('.view,.nav-btn').forEach(el=>el.classList.remove('active'));$('#'+v).classList.add('active');$(`.nav-btn[data-view="${v}"]`)?.classList.add('active');$('#pageTitle').textContent={dashboard:'Dashboard',eventos:'Eventos',produtos:'Produtos',clientes:'Clientes',patrimonio:'Patrimônio',financeiro:'Financeiro',config:'Configurações'}[v];render()}
function render(){renderDashboard();renderEvents();renderProducts();renderClients();renderAssets();renderFinance();renderConfig()}
function renderDashboard(){const ev=state.events, open=ev.filter(e=>e.status!=='finalizado'), done=ev.length-open.length, totals=ev.map(calcEvent);const fat=totals.reduce((a,b)=>a+b.total,0), lucro=fat*.328, consign=open.reduce((a,e)=>a+calcEvent(e).sent,0);$('#dashboard').innerHTML=`<div class="grid cols4"><div class="card metric"><div><small>EVENTOS EM ABERTO</small><h2>${open.length}</h2><small>Valor total: ${money(open.reduce((a,e)=>a+calcEvent(e).sent,0))}</small></div><div class="icon">🎉</div></div><div class="card metric"><div><small>EVENTOS FINALIZADOS</small><h2>${done}</h2><small>Mês atual</small></div><div class="icon">✅</div></div><div class="card metric"><div><small>VALOR EM CONSIGNAÇÃO</small><h2>${money(consign)}</h2><small>Em mercadorias</small></div><div class="icon">💲</div></div><div class="card metric"><div><small>LUCRO DO MÊS</small><h2>${money(lucro)}</h2><small>Margem: 32,8%</small></div><div class="icon">📊</div></div></div><div class="grid cols3" style="margin-top:16px"><div class="card"><h3>Faturamento</h3><h2>${money(fat)}</h2><div style="height:170px;display:flex;align-items:end;gap:8px">${[25,45,38,60,80,70,95,120,110,150,170,160].map(h=>`<div style="height:${h}px;flex:1;background:linear-gradient(#ffc400,#6b5200);border-radius:8px 8px 0 0"></div>`).join('')}</div></div><div class="card"><h3>Produtos mais consumidos</h3>${state.products.slice(0,6).map((p,i)=>`<p><span class="gold">●</span> ${p.name} <b style="float:right">${[32,21,15,12,10,10][i]}%</b></p>`).join('')}</div><div class="card"><h3>Agenda do dia</h3>${ev.map(e=>`<p><b>${e.start}</b> — ${e.client}<br><span class="status ${e.status==='finalizado'?'done':''}">${e.status==='finalizado'?'Finalizado':'Em andamento'}</span></p>`).join('')||'<p>Nenhum evento.</p>'}</div></div><div class="card" style="margin-top:16px"><h3>Últimos eventos</h3>${eventsTable(ev.slice(0,6))}</div><div class="fab-row"><button class="btn quick primary" onclick="openEventForm()">➕ <span><b>Novo Evento</b>Criar festa</span></button><button class="btn quick" onclick="setView('eventos')">🚚 <span><b>Carga Rápida</b>Lançar produtos</span></button><button class="btn quick" onclick="setView('eventos')">✅ <span><b>Fechamento</b>Conferir retornos</span></button><button class="btn quick" onclick="setView('clientes')">👤 <span><b>Novo Cliente</b>Histórico</span></button><button class="btn quick" onclick="setView('financeiro')">📄 <span><b>Relatórios</b>Ver resultados</span></button><button class="btn quick" onclick="setView('produtos')">📦 <span><b>Produtos</b>Gerenciar</span></button></div>`}
function eventsTable(list){return `<div class="table-wrap"><table class="table"><thead><tr><th>Nº Evento</th><th>Cliente</th><th>Data</th><th>Horário</th><th>Status</th><th>Total</th><th>Ações</th></tr></thead><tbody>${list.map(e=>`<tr><td>${e.id}</td><td>${e.client}</td><td>${dateBR(e.date)}</td><td>${e.start}</td><td><span class="status ${e.status==='finalizado'?'done':''}">${e.status==='finalizado'?'Finalizado':'Em andamento'}</span></td><td>${money(calcEvent(e).total)}</td><td><div class="actions"><button class="mini-btn" onclick="openEvent('${e.id}')">👁</button><button class="mini-btn" onclick="openEventForm('${e.id}')">✏️</button><button class="mini-btn" onclick="printA4('${e.id}')">📄</button><button class="mini-btn" onclick="printThermal('${e.id}')">🧾</button></div></td></tr>`).join('')}</tbody></table></div>`}
function dateBR(d){return d?d.split('-').reverse().join('/'):''}
function renderEvents(){const q=$('#globalSearch')?.value?.toLowerCase()||'';const list=state.events.filter(e=>(e.client+e.id+e.address).toLowerCase().includes(q));$('#eventos').innerHTML=`<div class="card"><div style="display:flex;justify-content:space-between;gap:12px;align-items:center"><h3>Eventos</h3><button class="btn primary" onclick="openEventForm()">+ Novo Evento</button></div>${eventsTable(list)}</div>`}
function renderProducts(){ $('#produtos').innerHTML=`<div class="card"><h3>Produtos</h3><div class="form-grid"><input id="pname" placeholder="Nome do produto"><input id="pprice" type="number" step="0.01" placeholder="Valor unitário"><button class="btn primary" onclick="addProduct()">Adicionar Produto</button></div>${simpleTable(state.products,['Produto','Preço','Estoque'],p=>[p.name,money(p.price),p.stock||0])}</div>`}
function renderAssets(){ $('#patrimonio').innerHTML=`<div class="card"><h3>Patrimônio</h3><div class="form-grid"><input id="aname" placeholder="Item emprestado"><input id="aprice" type="number" step="0.01" placeholder="Valor se não devolver"><input id="aqty" type="number" placeholder="Quantidade total"><button class="btn primary" onclick="addAsset()">Adicionar Item</button></div>${simpleTable(state.assets,['Item','Valor','Total'],a=>[a.name,money(a.price),a.qty])}</div>`}
function simpleTable(arr,heads,map){return `<div class="table-wrap" style="margin-top:16px"><table class="table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${arr.map(x=>`<tr>${map(x).map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function renderClients(){const clients={};state.events.forEach(e=>{clients[e.phone+e.client]??={name:e.client,phone:e.phone,total:0,count:0};clients[e.phone+e.client].total+=calcEvent(e).total;clients[e.phone+e.client].count++});$('#clientes').innerHTML=`<div class="grid cols2">${Object.values(clients).map(c=>`<div class="card"><h3>${c.name}</h3><p>${c.phone}</p><p>Total gasto: <b class="green">${money(c.total)}</b></p><p>Eventos: ${c.count}</p></div>`).join('')||'<div class="card">Nenhum cliente ainda.</div>'}</div>`}
function renderFinance(){const fat=state.events.reduce((a,e)=>a+calcEvent(e).total,0);$('#financeiro').innerHTML=`<div class="grid cols3"><div class="card"><h3>Total Faturado</h3><h2 class="green">${money(fat)}</h2></div><div class="card"><h3>Custos Estimados</h3><h2 class="red">${money(fat*.672)}</h2></div><div class="card"><h3>Lucro Bruto</h3><h2 class="green">${money(fat*.328)}</h2></div></div><div class="card" style="margin-top:16px">${eventsTable(state.events)}</div>`}
function renderConfig(){const c=state.company;$('#config').innerHTML=`<div class="card"><h3>Dados da Empresa</h3><div class="form-grid">${Object.keys(c).map(k=>`<div class="field"><label>${k}</label><input id="cfg-${k}" value="${c[k]}"></div>`).join('')}<button class="btn primary" onclick="saveConfig()">Salvar Configurações</button></div></div>`}
function openModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')} function closeModal(){$('#modal').classList.add('hidden')}
function openEventForm(id){const e=state.events.find(x=>x.id===id)||{id:'',client:'',phone:'',date:new Date().toISOString().slice(0,10),start:'15:00',end:'',address:'',notes:'',deliveryFee:0,serviceFee:0,otherFee:0,status:'em_andamento',items:state.products.map(p=>({productId:p.id,sent:0,returned:0})),assets:state.assets.map(a=>({assetId:a.id,sent:0,returned:0}))};openModal(`<h2>${id?'Editar Evento':'Novo Evento'}</h2><div class="form-grid"><input id="eid" type="hidden" value="${e.id}">${field('Cliente','client',e.client)}${field('Telefone','phone',e.phone)}${field('Data','date',e.date,'date')}${field('Início','start',e.start,'time')}${field('Término','end',e.end,'time')}${field('Endereço','address',e.address)}${field('Taxa entrega','deliveryFee',e.deliveryFee,'number')}${field('Taxa serviço','serviceFee',e.serviceFee,'number')}<div class="field full"><label>Observações</label><textarea id="notes">${e.notes||''}</textarea></div><button class="btn primary" onclick="saveEvent()">Salvar Evento</button></div>`) }
function field(l,id,v,type='text'){return `<div class="field"><label>${l}</label><input id="${id}" type="${type}" value="${v??''}"></div>`}
function saveEvent(){const id=$('#eid').value||`EVT-${String(Date.now()).slice(-6)}`;let e=state.events.find(x=>x.id===id);if(!e){e={id,items:state.products.map(p=>({productId:p.id,sent:0,returned:0})),assets:state.assets.map(a=>({assetId:a.id,sent:0,returned:0})),status:'em_andamento'};state.events.unshift(e)}['client','phone','date','start','end','address','notes'].forEach(k=>e[k]=$('#'+k).value);['deliveryFee','serviceFee','otherFee'].forEach(k=>e[k]=+($('#'+k)?.value||0));store.set(state);closeModal();render();toast('Evento salvo com sucesso')}
function openEvent(id){const e=state.events.find(x=>x.id===id);const c=calcEvent(e);openModal(`<div class="event-header"><div class="card"><h2>${e.client}</h2><p class="gold">${e.id} • ${dateBR(e.date)} • ${e.start} às ${e.end||'--:--'}</p><p>${e.address}</p><p>${e.notes||''}</p></div><div class="card"><h3>Total Geral</h3><h1 class="gold">${money(c.total)}</h1><p>Produtos: ${money(c.products)}<br>Patrimônio: ${money(c.missing)}<br>Taxas: ${money(c.fees)}</p></div></div><div class="tabs"><button class="tab active" onclick="eventTab('${id}','carga',this)">Carga Enviada</button><button class="tab" onclick="eventTab('${id}','retorno',this)">Retorno</button><button class="tab" onclick="eventTab('${id}','patrimonio',this)">Patrimônio</button><button class="tab" onclick="eventTab('${id}','fechamento',this)">Fechamento</button></div><div id="eventTab"></div>`);eventTab(id,'carga')}
function eventTab(id,type,btn){$$('.tab').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');const e=state.events.find(x=>x.id===id);let html='';if(type==='carga'||type==='retorno'){html=`<div class="card">${e.items.map(it=>{const p=state.products.find(x=>x.id===it.productId);return `<div class="item-row"><b>${p.name}<br><small>${money(p.price)}</small></b><span>Enviado</span>${qty(id,it.productId,'sent',it.sent,'item')}<span>Retorno</span>${qty(id,it.productId,'returned',it.returned,'item')}</div>`}).join('')}<button class="btn primary" onclick="saveLine('${id}')">Salvar Alterações</button></div>`}if(type==='patrimonio'){html=`<div class="card">${e.assets.map(it=>{const p=state.assets.find(x=>x.id===it.assetId);return `<div class="item-row"><b>${p.name}<br><small>${money(p.price)}</small></b><span>Enviado</span>${qty(id,it.assetId,'sent',it.sent,'asset')}<span>Devolvido</span>${qty(id,it.assetId,'returned',it.returned,'asset')}</div>`}).join('')}<button class="btn primary" onclick="saveLine('${id}')">Salvar Patrimônio</button></div>`}if(type==='fechamento'){html=`<div class="card"><h2>Resumo de Fechamento</h2>${receiptHTML(e,false)}<div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:14px"><button class="btn" onclick="printA4('${id}')">Gerar PDF / A4</button><button class="btn" onclick="printThermal('${id}')">Imprimir Térmica</button><button class="btn green" onclick="sendWhats('${id}')">Enviar WhatsApp</button><button class="btn primary" onclick="finishEvent('${id}')">Finalizar Festa</button></div></div>`}$('#eventTab').innerHTML=html}
function qty(eid,pid,k,v,kind){return `<div class="qty"><button onclick="chgQty('${eid}','${pid}','${k}',-1,'${kind}')">−</button><input data-eid="${eid}" data-pid="${pid}" data-kind="${kind}" data-key="${k}" value="${v||0}" type="number"><button onclick="chgQty('${eid}','${pid}','${k}',1,'${kind}')">+</button></div>`}
function chgQty(eid,pid,k,n,kind){const inp=$(`input[data-eid="${eid}"][data-pid="${pid}"][data-key="${k}"][data-kind="${kind}"]`);inp.value=Math.max(0,(+inp.value||0)+n)}
function saveLine(id){const e=state.events.find(x=>x.id===id);$$(`input[data-eid="${id}"]`).forEach(inp=>{const arr=inp.dataset.kind==='asset'?e.assets:e.items;let it=arr.find(x=>(x.productId||x.assetId)===inp.dataset.pid);it[inp.dataset.key]=+inp.value||0});store.set(state);toast('Alterações salvas');openEvent(id)}
function receiptHTML(e,full=true){const c=calcEvent(e);return `<div class="receipt"><div class="r-head"><div><img src="assets/logo-pitstop.jpeg"><h2>${state.company.name}</h2><p>${state.company.address}<br>${state.company.city}<br>CNPJ: ${state.company.cnpj}<br>${state.company.phone} • ${state.company.instagram}</p></div><div><h1>NOTA DE FECHAMENTO</h1><h2 class="gold">EVENTO EM CONSIGNAÇÃO</h2><h1>${e.id}</h1></div></div><p><b>Cliente:</b> ${e.client} &nbsp; <b>Telefone:</b> ${e.phone}<br><b>Data:</b> ${dateBR(e.date)} &nbsp; <b>Horário:</b> ${e.start} às ${e.end||'--:--'}<br><b>Endereço:</b> ${e.address}</p><h3>Produtos</h3><table><thead><tr><th>Produto</th><th>Enviado</th><th>Retorno</th><th>Consumido</th><th>Unit.</th><th>Total</th></tr></thead><tbody>${e.items.map(it=>{const p=state.products.find(x=>x.id===it.productId), cons=Math.max(0,it.sent-it.returned);return `<tr><td>${p.name}</td><td>${it.sent}</td><td>${it.returned}</td><td>${cons}</td><td>${money(p.price)}</td><td>${money(cons*p.price)}</td></tr>`}).join('')}</tbody></table><h3>Patrimônio</h3><table><thead><tr><th>Item</th><th>Enviado</th><th>Devolvido</th><th>Faltante</th><th>Total</th></tr></thead><tbody>${e.assets.map(it=>{const p=state.assets.find(x=>x.id===it.assetId), f=Math.max(0,it.sent-it.returned);return `<tr><td>${p.name}</td><td>${it.sent}</td><td>${it.returned}</td><td>${f}</td><td>${money(f*p.price)}</td></tr>`}).join('')}</tbody></table><p><b>Taxa de entrega:</b> ${money(e.deliveryFee)} • <b>Taxa de serviço:</b> ${money(e.serviceFee)} • <b>Outras:</b> ${money(e.otherFee)}</p><div class="total">TOTAL GERAL ${money(c.total)}</div>${full?'<p><br>Conferido por: _________________________ &nbsp;&nbsp; Cliente: _________________________</p>':''}</div>`}
function thermalHTML(e){const c=calcEvent(e);return `<div class="thermal"><img src="assets/logo-pitstop.jpeg"><h2>${state.company.name}<br>NOTA DE FECHAMENTO</h2><p>${state.company.address}<br>CNPJ: ${state.company.cnpj}</p><hr><b>${e.id}</b><p>${e.client}<br>${e.phone}<br>${dateBR(e.date)} ${e.start} às ${e.end||'--:--'}</p><hr><table>${e.items.map(it=>{const p=state.products.find(x=>x.id===it.productId), cons=Math.max(0,it.sent-it.returned);return `<tr><td>${p.name}</td><td>${cons}</td><td>${money(cons*p.price)}</td></tr>`}).join('')}</table><hr><p>Produtos: ${money(c.products)}<br>Não devolvidos: ${money(c.missing)}<br>Taxas: ${money(c.fees)}</p><div class="big">${money(c.total)}</div><p>Conferido por: __________<br>Cliente: _______________</p><hr><center>${state.company.phone}<br>${state.company.instagram}</center></div>`}
function printA4(id){const e=state.events.find(x=>x.id===id);$('#printArea').innerHTML=receiptHTML(e);window.print()} function printThermal(id){const e=state.events.find(x=>x.id===id);$('#printArea').innerHTML=thermalHTML(e);window.print()}
function sendWhats(id){const e=state.events.find(x=>x.id===id), c=calcEvent(e);const txt=`Fechamento ${e.id}%0ACliente: ${e.client}%0ATotal: ${money(c.total)}%0APitStop Cohab`;window.open(`https://wa.me/?text=${txt}`,'_blank')}
function finishEvent(id){const e=state.events.find(x=>x.id===id);e.status='finalizado';store.set(state);toast('Festa finalizada');closeModal();render()}
function addProduct(){state.products.push({id:uid('prod'),name:$('#pname').value,price:+$('#pprice').value||0,stock:0});store.set(state);render();toast('Produto adicionado')}function addAsset(){state.assets.push({id:uid('pat'),name:$('#aname').value,price:+$('#aprice').value||0,qty:+$('#aqty').value||0});store.set(state);render();toast('Patrimônio adicionado')}function saveConfig(){Object.keys(state.company).forEach(k=>state.company[k]=$('#cfg-'+k).value);store.set(state);render();toast('Configurações salvas')}
window.setView=setView;window.openEventForm=openEventForm;window.openEvent=openEvent;window.eventTab=eventTab;window.chgQty=chgQty;window.saveLine=saveLine;window.printA4=printA4;window.printThermal=printThermal;window.sendWhats=sendWhats;window.finishEvent=finishEvent;window.addProduct=addProduct;window.addAsset=addAsset;window.saveConfig=saveConfig;
$$('.nav-btn').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#newEventBtn').onclick=()=>openEventForm();$('#closeModal').onclick=closeModal;$('#toggleMenu').onclick=()=>$('.sidebar').classList.toggle('open');$('#seedBtn').onclick=()=>{localStorage.removeItem('pitstopEventosV1');state=seed();render();toast('Exemplo restaurado')};$('#globalSearch').oninput=renderEvents;render();
